# this file is intended for interactive development only

services:
  autopatch:
    build: ./src
    container_name: autopatch
    env_file:
      - ./src/.env
    volumes:
      - ./afl-2.52b:/app/afl-2.52b
      - ./src/bugLog:/app/src/bugLog
      - ./assets/input_codebase:/app/src/codebase
      - ./src/executables:/app/src/executables
      - ./src/executables_afl:/app/src/executables_afl
      - ./src/input:/app/src/input
      - ./src/patched_codes:/app/src/patched_codes
    working_dir: /app
  autopatch-fuzzing-service:
    build: ./src/fuzzing-service
    container_name: autopatch-fuzzing-service
    environment:
      - FUZZ_SVC_CONFIG=/app/config/config.json
    volumes:
      - ./bin:/app/bin:ro
      - ./assets/input_codebase:/app/data/codebase:ro
      - ./src/fuzzing-service/config:/app/config:ro
      - ./src/fuzzing-service/logs:/app/logs:rw
      - ./src/fuzzing-service/data:/app/data:rw
      - ./src/fuzzing-service/seed_input:/app/data/seed_input:ro
    working_dir: /app
