---
# docker-compose.yaml

services:
  autopatch-llm-dispatch-service:
    image: ghcr.io/sysec-uic/autopatch-llm/llm-dispatch-service:0.7.0
    networks:
      - autopatch-llm_autopatch-docker-network
    build: ./src/llm-dispatch-service
    container_name: autopatch-llm-dispatch-service
    environment:
      - LLM_DISPATCH_CONFIG=/app/config/config.json
    env_file:
      - ./src/llm-dispatch-service/.env
    volumes:
      - ./src/llm-dispatch-service/config:/app/config:ro
      - ./src/llm-dispatch-service/log:/app/log:rw
      - ./src/llm-dispatch-service/data:/app/data:ro
      - ./assets/input_codebase:/app/input_codebase:ro
    working_dir: /app
  autopatch-code-property-graph-generator:
    image: ghcr.io/sysec-uic/autopatch-llm/code-property-graph-generator:0.7.0
    networks:
      - autopatch-llm_autopatch-docker-network
    build: ./src/code-property-graph-generator
    container_name: autopatch-code-property-graph-generator
    environment:
      - CPG_SVC_CONFIG=/app/config/config.json
    volumes:
      - ./src/code-property-graph-generator/config:/app/config:ro
      - ./src/code-property-graph-generator/log:/app/log:rw
      - ./src/code-property-graph-generator/data:/app/data:rw
      - ./assets/input_codebase:/app/input_codebase:ro
    working_dir: /app
  autopatch-fuzzing-service:
    image: ghcr.io/sysec-uic/autopatch-llm/fuzzing-service:0.7.0
    networks:
      - autopatch-llm_autopatch-docker-network
    build: ./src/fuzzing-service
    container_name: autopatch-fuzzing-service
    environment:
      - FUZZ_SVC_CONFIG=/app/config/config.json
    volumes:
      - ./src/fuzzing-service/config:/app/config:ro
      - ./src/fuzzing-service/log:/app/log:rw
      - ./src/fuzzing-service/data:/app/data:rw
      - ./bin/executables_afl:/app/bin/executables_afl:rw
      - ./assets/input_codebase:/app/input_codebase:ro
      - ./src/fuzzing-service/seed_input:/app/seed_input:ro
    working_dir: /app
  autopatch-patch-evaluation-service:
    image: ghcr.io/sysec-uic/autopatch-llm/patch-evaluation-service:0.7.0
    networks:
      - autopatch-llm_autopatch-docker-network
    build: ./src/patch-evaluation-service
    container_name: autopatch-patch-evaluation-service
    environment:
      - PATCH_EVAL_SVC_CONFIG=/app/config/config.json
    volumes:
      - ./src/patch-evaluation-service/config:/app/config:ro
      - ./src/patch-evaluation-service/log:/app/log:rw
      - ./src/patch-evaluation-service/data:/app/data:rw
      - ./src/patch-evaluation-service/bin:/app/bin:rw
      - ./assets/input_codebase:/app/input_codebase:ro
    working_dir: /app
  mosquitto:
    image: eclipse-mosquitto:2.0.20
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    networks:
      - autopatch-llm_autopatch-docker-network
    ports:
      - "1883:1883" # MQTT
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw

networks:
  autopatch-llm_autopatch-docker-network:
    external: true
    driver: bridge