[project]
name = "autopatch"
version = "0.1.0"
requires-python = ">=3.12.3"
description = ""

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.isort]
src_paths = ["src", "test"]
profile = "black"
