version: '3'

includes:
   autopatch:
      taskfile: ./src/Taskfile.yml
      dir: ./src
   fuzzing-service:
      taskfile: ./src/fuzzing-service/Taskfile.yml
      dir: ./src/fuzzing-service
   llm-dispatch:
      taskfile: ./src/llm-dispatch/Taskfile.yml
      dir: ./src/llm-dispatch
   autopatchdatatypes:
      taskfile: ./src/autopatchdatatypes/Taskfile.yml
      dir: ./src/autopatchdatatypes

tasks:
   test:
      desc: Run tests
      cmds:
         - "echo 'Running tests...'"
         - pytest
   lint:
      desc: Run linter
      cmds:
      - "echo 'Running linter...'"
      - "echo Not Yet Implemented"
      # - task: fuzzing-service:lint
   build-install-datatypes:
      desc: Build and install datatypes package
      cmds:
      - "echo 'Building datatypes...'"
      - task: autopatchdatatypes:build
      - task: autopatchdatatypes:install