version: '3'

includes:
 autopatch:
    taskfile: ./src/Taskfile.yml
    dir: ./src
 fuzzing-svc:
    taskfile: ./src/fuzzing-svc/Taskfile.yml
    dir: ./src/fuzzing-svc
 llm-dispatch:
    taskfile: ./src/llm-dispatch/Taskfile.yml
    dir: ./src/llm-dispatch

tasks:
   test:
      desc: Run tests
      cmds:
         - "echo 'Running tests...'"
         - "echo Not Yet Implemented"
         # - task: autopatch:test
   lint:
      desc: Run linter
      cmds:
      - "echo 'Running linter...'"
      - "echo Not Yet Implemented"
      # - task: autopatch:lint