version: '3'

tasks:

  build:
    desc: install AutoPatch dependencies
    cmds:
      - echo "hello AutoPatch!"
      - pip install -r requirements.txt

  create-required-dirs:
    desc: create required directories
    cmds:
      - mkdir -p bugLog/
      - mkdir -p codebase/
      - mkdir -p executables/
      - mkdir -p executables_afl/
      - mkdir -p input/
      - mkdir -p patched_codes/

  rm-temp-dirs:
    desc: remove temporary directories
    cmds:
      - rm -rf bugLog/
      - rm -rf executables/
      - rm -rf executables_afl/
      - rm -rf patched_codes/
