version: '3'

tasks:
  core-dump-notification-config:
    summary: Configure core dump notification if running in GCE
    desc: |
      This section is for when afl2.52b runs in GCE, it may display a message like
      
      Hmm, your system is configured to send core dump notifications to an
      external utility. This will cause issues: there will be an extended delay
      between stumbling upon a crash and having this information relayed to the
      fuzzer via the standard waitpid() API.

      To avoid having crashes misinterpreted as timeouts, please log in as root
      and temporarily modify /proc/sys/kernel/core_pattern, like so:

      echo core >/proc/sys/kernel/core_pattern
    cmds:
      - echo 'you need to login as root on the host system outside of the devcontainer and run \# echo core >/proc/sys/kernel/core_pattern'
  run:
    desc: run autopatch-fuzzingservice
    generates:
      - autopatch-fuzzingservice.log
    preconditions:
      - stat config.json
    cmds:
      - python ./fuzzing_service.py
  
  debug:
    desc: debug autopatch-fuzzingservice
    generates:
      - autopatch-fuzzingservice.log
    preconditions:
      - stat config.json
    cmds:
      - python -m pdb ./fuzzing_service.py
  
  test:
    desc: test autopatch-fuzzingservice
    cmds:
      - pytest
