version: '3'

tasks:
  debug:
    desc: debug autopatch-fuzzingservice
    generates:
      - log/autopatch-fuzzingservice.log
    preconditions:
      - stat config/config.json
    cmds:
      - python -m pdb ./fuzzing_service.py
  test:
    desc: test autopatch-fuzzingservice
    cmds:
      - pytest
  install:
    desc: install autopatch-fuzzingservice
    cmds:
      - pip install -r requirements.txt  --break-system-packages
  clean:
    desc: scrubs the workspace, old debug log files etc.
    cmds:
      - truncate -s 0 ./log/autopatch.fuzzing-service.debug.log
