version: '3'

env:
  ARGS: --break-system-packages # Use this If you are installing packages using the Taskfile Extension for VSCode UI and devcontainer

tasks:
  build:
    desc: Build AutoPatch Shared
    cmds:
      - echo "Building AutoPatch Shared"
      - python -m build
  install:
    desc: Install AutoPatch Shared
    cmds:
      - echo "Installing AutoPatch Shared"
      - pip install {{.CLI_ARGS}} $ARGS ./dist/*.whl
  uninstall:
    desc: uninstall autopatchshared
    cmds:
      - pip uninstall -y autopatchshared-*-py3-none-any.whl --break-system-packages
  clean:
    desc: Clean AutoPatch shared
    cmds:
      - echo "Cleaning AutoPatch shared"
      - rm -rf ./dist
      - rm -rf ./build
      - rm -rf ./autopatchpubsub.egg-info
