version: '3'

tasks:
  build:
    desc: build autopatchpubsub
    cmds:
      - python -m build
  install:
    desc: install autopatchpubsub
    cmds:
      - pip install -r requirements.txt --break-system-packages
