version: '3'

tasks:
  chatgpt-hello-world:
    dotenv: ['.env']
    cmds:
      - python invoke-chatgpt-API-hello-world.py
  install:
    desc: install autopatch-llmdispatch
    cmds:
      - pip install -r requirements.txt