version: '3'

tasks:
  run:
    desc: run autopatch-patch-evaluation-service
    generates:
      - ./log/autopatch.patch-evaluation-service.debug.log
    preconditions:
      - stat ./config/config.json
    cmds:
      - python patch_evaluation_service.py
  
  debug:
    desc: debug autopatch-patch-evaluation-service
    generates:
      - ./log/autopatch.patch-evaluation-service.debug.log
    preconditions:
      - stat ./config/config.json
    cmds:
      - python -m pdb ./patch_evaluation_service.py
  
  test:
    desc: test autopatch-patch-evaluation-service
    cmds:
      - pytest

  clean:
    desc: scrubs the workspace, old debug log files etc.
    cmds:
      - truncate -s 0 ./log/autopatch.patch-evaluation-service.debug.log
  
  rm-executables:
    desc: removes the subdirectories in the executables directory.
    cmds:
      - rm -r ./executables/*
  rm-dirs-for-dev:
    desc: removes the subdirectories within the executables and data directories.
    cmds:
      - rm -r ./executables/*
      - rm -r ./data/*
