version: '3'

env:
  ARGS: --break-system-packages # Use this If you are installing packages using the Taskfile Extension for VSCode UI and devcontainer

tasks:
  install-devtools:
    desc: install AutoPatch dev dependencies
    cmds:
      - echo "If you are running this manually and installing in a VM instead of a devcontainer, use a virtual environment and activate it first."
      - pip install {{.CLI_ARGS}} $ARGS -r ./dev-requirements.txt
