version: '3'

tasks:
  build:
    desc: install AutoPatch prod dependencies
    cmds:
      - echo "Hello AutoPatch!"
      - pip install {{.CLI_ARGS}} -r /app/src/requirements.txt

  install-devtools:
    desc: install AutoPatch dev dependencies
    cmds:
      - task: build
      - pip install {{.CLI_ARGS}} -r /app/src/dev-requirements.txt

  run-autopatch:
    desc: run AutoPatch
    cmds:
      - python /app/src/main.py
  
  debug-autopatch:
    desc: debug AutoPatch
    cmds:
      - python -m pdb /app/src/main.py