# .github/workflows/build-datatypes-package.yml
name: Build and Publish Python Package
run-name: Build and Publish Python Package by @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'src/autopatchdatatypes/pyproject.toml'
      - 'src/autopatchdatatypes/autopatchdatatypes/**'

env:
  PYTHON_VERSION: 3.12.3
  BUILD_TOOLS_VERSION: 1.2.2.post1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sparse-checkout: |
            src/autopatchdatatypes/pyproject.toml
            src/autopatchdatatypes/autopatchdatatypes
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Upgrade pip and install build module
        run: |
          python -m pip install --upgrade pip
          pip install build==${{ env.BUILD_TOOLS_VERSION }}
      - name: Build AutoPatch Datatypes Package
        working-directory: src/autopatchdatatypes
        run: python -m build
      - name: Upload Build Artifact
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1
        with:
          name: python-package-build
          path: src/autopatchdatatypes/dist