# .github/workflows/build-and-push-docker-images.yml
---
name: Build and Push Docker Image
run-name: Build and Push Docker Image by @${{ github.actor }}

on:
  push:
    branches:
      - feature/docker-container-releases
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
            - 'llm-dispatch-service'
            - 'code-property-graph-generator'
            - 'fuzzing-service'
            - 'patch-patch-evaluation-service'
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src/${{ matrix.image}}
          push: false
        #   push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
