---
name: "pre-release"
run-name: "Pre Release by @${{ github.actor }}"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
      - "feature/automatic-pre-release-latest-dev-build"

env:
  PYTHON_VERSION: "3.12.3"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - name: arduino/setup-task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            .github
            src
            Taskfile.yml
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Upgrade pip 
        run: |
          python -m pip install --upgrade pip
      - name: Install build module
        run: |
          pip install build
      - name: Build AutoPatch.Datatypes Package
        run: task autopatchdatatypes:build
      - name: Install AutoPatch.Datatypes Package
        run: task autopatchdatatypes:install
      - name: "Build & test"
        run: |
          task test
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.whl
            autopatchdatatypes-*.tar.gz
