# .github/workflows/release.yml
---
name: Tagged-Release
run-name: Tagged Release by @${{ github.actor }}

on:
  push:
    tags:
      - "v*"

env:
  PYTHON_VERSION: "3.12.3"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Harden-Runner
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit
      - name: arduino/setup-task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          sparse-checkout: |
            .github
            src
            Taskfile.yml
      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Upgrade pip 
        run: |
          python -m pip install --upgrade pip
      - name: Install build module
        run: |
          pip install build==1.2.2.post1
      - name: Install test module
        run: |
          pip install pytest==8.3.4
      - name: Install test module
        run: |
          task install-package-dependencies
      - name: "Build & test"
        run: |
          task test
      - name: Automatic Tagged Release
        uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            **/*.whl
            **/autopatchdatatypes-*.tar.gz
            **/autopatchpubsub-*.tar.gz
